version: 2.1

orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.15.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build
      - run:
          command: npm run test
          name: Run Tests
      - run:
          command: node generateUserScript.js > ./docs/fateOfAllFools.user.js
          name: Generate New User Script
      - run:
          command: |
            cp ./public/fateOfAllFools.js docs/
            cp ./public/fateOfAllFools.css docs/
          name: Prep Assets for Release
      - run:
          command: |
            git config --global user.email "circleci@circleci.com"
            git config --global user.name "Circle CI"
            git add docs/*
            git commit -m "[skip ci] Publishing build ${CIRCLE_BUILD_NUM}"
            git push
          name: Commit

workflows:
  build_test:
    jobs:
      - build_and_test
