exports.VOLATILE_CLASSES = {
  ARMOR_SPAN_AVOID_CLASS:  '.XvpsT',
  ATTTUNEMENT_COMPLETE_CLASS: '.Ly0Lf',
  DEEPSIGHT_BORDER_CLASS:  '.rF59A',
  ELEMENT_ICON_CLASS:      '.e0VY8',
  MASTERWORK_CLASS:        '.EJ0gV',
  POWER_LEVEL_CLASS:       '.SLO2o'
}