exports.VOLATILE_CLASSES = {
  ARMOR_SPAN_AVOID_CLASS:     '.XvpsTGeC',
  ATTTUNEMENT_COMPLETE_CLASS: '.Ly0Lf',
  DEEPSIGHT_BORDER_CLASS:     '.rF59AvCY',
  ELEMENT_ICON_CLASS:         '.e0VY8WPa',
  MASTERWORK_CLASS:           '.EJ0gVh8G',
  MASTERWORK_CLASS_EXO:       '.ocMSkp02',
  POWER_LEVEL_CLASS:          '.SLO2oppG'
}